# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 13:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_files_userfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfile',
            old_name='usernamer',
            new_name='user',
        ),
    ]
