# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_post_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=2),
        ),
    ]
